---
- name: Reboot Playbook
  hosts: lin
  become: yes

  tasks:
  - name: Ping test
    ping:

  - name: Reboot my Servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait Servers Online
    wait_for:
       hosts: "{{ inventory_hostname }}"
       state: started
       delay: 5
       timeout: 40
    delegate_to: 127.0.0.1
